# Generated by Django 5.0.6 on 2024-08-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='return_date',
            field=models.DateField(null=True),
        ),
    ]
